spring:
  datasource:
    url: ${PDF_BATCH_DATABASE_URL:jdbc:h2:file:./.local-data/database/pdfbatch;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
    username: ${PDF_BATCH_DATABASE_USER:sa}
    password: ${PDF_BATCH_DATABASE_PASSWORD:}
    driver-class-name: org.h2.Driver

pdf-batch:
  storage-root: ${PDF_BATCH_STORAGE_ROOT:.local-data/jobs}
